// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC4jigclG4ItL8ZljXXQD14l4ZJUtVNkH4",        
    appId: "1:975930504760:web:2900511c6f952601e418cd",
    messagingSenderId: "975930504760",        
    projectId: "wondershare-73bb9",
    storageBucket: "wondershare-73bb9.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBmfu5lb2yfw7fSctlgfhYFSpOrx8B8EIs",
    appId: "1:975930504760:android:9387b87175b7d1fbe418cd",
    messagingSenderId: "975930504760",        
    projectId: "wondershare-73bb9",
    storageBucket: "wondershare-73bb9.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6fQL6gp2QNlpqBCNYWIR27VzMKkmA_c',
    appId: '1:975930504760:ios:646bc7b80cc49e01e418cd',
    messagingSenderId: '975930504760',
    projectId: 'wondershare-73bb9',
    storageBucket: "wondershare-73bb9.appspot.com",
    iosBundleId: 'com.example.wondershare',
  );

  
  
}
